module DatadogThreadTracer
  class ThreadTracer
    def initialize: () -> void

    def trace: (?trace_name: string, ?thread_args: untyped) { () -> untyped } -> untyped

    def join_threads: () -> untyped
  end
end
