name: Publish gem to rubygems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo-name: sue445/datadog_thread_tracer
      gem-name:  datadog_thread_tracer
    permissions:
      contents: write
      id-token: write
